// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SkiEquipmentRental20.Models;

public partial class Equipment
{
    public int EquipmentId { get; set; }

    public string Name { get; set; }

    public string Type { get; set; }

    public decimal Price { get; set; }

    public int Quantity { get; set; }

    public int? StatusId { get; set; }

    public bool Isdelited { get; set; }

    public virtual ICollection<Rental> Rentals { get; set; } = new List<Rental>();

    public virtual Status Status { get; set; }
}