// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SkiEquipmentRental20.Models;

public partial class Rental
{
    public int RentalId { get; set; }

    public int UserId { get; set; }

    public int EquipmentId { get; set; }

    public DateTime StartDatetime { get; set; }

    public DateTime EndDatetime { get; set; }

    public decimal TotalCost { get; set; }

    public decimal Deposit { get; set; }

    public virtual Equipment Equipment { get; set; }

    public virtual ICollection<Review> Reviews { get; set; } = new List<Review>();

    public virtual Appuser User { get; set; }
}