// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SkiEquipmentRental20.Models;

public partial class Review
{
    public int ReviewId { get; set; }

    public int Rating { get; set; }

    public string Comment { get; set; }

    public DateTime? ReviewDate { get; set; }

    public int? RentalId { get; set; }

    public virtual Rental Rental { get; set; }
}