// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SkiEquipmentRental20.Models;

public partial class Role
{
    public int RoleId { get; set; }

    public string Position { get; set; }

    public virtual ICollection<Appuser> Appusers { get; set; } = new List<Appuser>();
}