// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SkiEquipmentRental20.Models;

public partial class Status
{
    public int StatusId { get; set; }

    public string CurrentStatus { get; set; }

    public DateTime? StatusChangeDate { get; set; }

    public virtual ICollection<Equipment> Equipment { get; set; } = new List<Equipment>();
}